baseURL: "https://awinml.github.io"
languageCode: en-us
title: Ashwin Mathur
paginate: 5
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 5
    - identifier: about
      name: About
      url: /about
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 30
    - identifier: resume
      name: Resume
      url: https://example.org
      params:
        external: true
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-ZE0Y3K4S3E

minify:
  disableXML: true
  minifyOutput: true







params:
  showtoc: true
  tocopen: True
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: True
  ShowWordCount: False
  ShowRssButtonInSectionTermList: False
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: True
  hidemeta: false
  hideSummary: false
  TocSide: 'left'
  
  
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  
  title: Ashwin Mathur
  description: "Ashwin Mathur Portfolio"
  keywords: [Ashwin Mathur, Blog, Portfolio, Data Science, awinml]
  author: Ashwin Mathur
  images: ["/home/profile-pic.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: True






  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon_io/favicon.ico"
    favicon16x16: "/favicon_io/favicon-16x16.png"
    favicon32x32: "/favicon_io/favicon-32x32.png"
    apple_touch_icon: "/favicon_io/apple-touch-icon.png"
    safari_pinned_tab: "/favicon_io/apple-touch-icon.png"

  label:
    text: "Ashwin Mathur"
    #icon: /favicon_io/apple-touch-icon.png
    #iconHeight: 100

  # profile-mode
  profileMode:
    enabled: True # needs to be explicitly set
    title: Ashwin Mathur
    subtitle: |
      I am a final year postgraduate student currently pursuing a Masters in Data Science from Fergusson College, Pune. I am interested in working on researching and implementing Natural Language Processing and Machine Learning solutions, with applications to the finance domain.



    imageUrl: "/home/profile-pic.png"
    imageWidth: 180
    imageHeight: 180
    imageTitle: Profile Picture
    buttons:
      - name: Blog
        url: blog
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/ashwin-mathur-ds/"
    - name: email
      url: "mailto:ashwinm400@gmail.com"
    - name: github
      url: "https://github.com/awinml"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page


  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content", "blog", "projects", "about"]



pygmentsUseClasses: true
markup:
  # allow HTML in MD
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
    

